# Generated by Django 3.0.2 on 2020-01-23 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader', '0003_auto_20200123_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='info',
        ),
    ]
